image: Visual Studio 2022

version: 5.0.0.{build}

init:
  - git config --global core.autocrlf input

install:
  # Install OpenGL
  - "powershell ./install-opengl.ps1"
configuration: Release

build_script:
  - build.cmd -t RunCITests

on_finish:
  - "powershell ./install-opengl.ps1 uninstall"
